let nom1 = document.querySelector('.spp1')
let nom2 = document.querySelector('.spp2')
let nom3 = document.querySelector('.spp3')
let nom4 = document.querySelector('.spp4')
let nom5 = document.querySelector('.spp5')
let bg1 = document.querySelector('.header__father01')
let bg2 = document.querySelector('.header__father01')
let bg3 = document.querySelector('.header__father01')
let bg4 = document.querySelector('.header__father01')
let bg5 = document.querySelector('.header__father01')

nom1.addEventListener('click', function(){
    nom1.classList.add('img1')
    nom2.classList.remove('img2')
    nom3.classList.remove('img3')
    nom4.classList.remove('img4')
    nom5.classList.remove('img5')
    bg1.classList.add('bg1')
    bg2.classList.remove('bg2')
    bg3.classList.remove('bg3')
    bg4.classList.remove('bg4')
    bg5.classList.remove('bg5')
})
nom2.addEventListener('click', function(){
    nom1.classList.remove('img1')
    nom2.classList.add('img2')
    nom3.classList.remove('img3')
    nom4.classList.remove('img4')
    nom5.classList.remove('img5')
    bg1.classList.remove('bg1')
    bg2.classList.add('bg2')
    bg3.classList.remove('bg3')
    bg4.classList.remove('bg4')
    bg5.classList.remove('bg5')
})
nom3.addEventListener('click', function(){
    nom1.classList.remove('img1')
    nom2.classList.remove('img2')
    nom3.classList.add('img3')
    nom4.classList.remove('img4')
    nom5.classList.remove('img5')
    bg1.classList.remove('bg1')
    bg2.classList.remove('bg2')
    bg3.classList.add('bg3')
    bg4.classList.remove('bg4')
    bg5.classList.remove('bg5')
})
nom4.addEventListener('click', function(){
    nom1.classList.remove('img1')
    nom2.classList.remove('img2')
    nom3.classList.remove('img3')
    nom4.classList.add('img4')
    nom5.classList.remove('img5')
    bg1.classList.remove('bg1')
    bg2.classList.remove('bg2')
    bg3.classList.remove('bg3')
    bg4.classList.add('bg4')
    bg5.classList.remove('bg5')
})
nom5.addEventListener('click', function(){
    nom1.classList.remove('img1')
    nom2.classList.remove('img2')
    nom3.classList.remove('img3')
    nom4.classList.remove('img4')
    nom5.classList.add('img5')
    bg1.classList.remove('bg1')
    bg2.classList.remove('bg2')
    bg3.classList.remove('bg3')
    bg4.classList.remove('bg4')
    bg5.classList.add('bg5')
})

